version: '3.8'

services:
  playing_cards:
    image: playing_cards
    container_name: playing_cards
    build:
      context: "."
      dockerfile: "docker/Dockerfile"
    ports:
      - "3100:3100"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      SESSION_ID_COOKIE_KEY: ${SESSION_ID_COOKIE_KEY}
      TOKEN_COOKIE_KEY: ${TOKEN_COOKIE_KEY}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      MONGO_DB_HOST: ${MONGO_DB_HOST}
      MONGO_DB_USER: ${MONGO_DB_USER}
      MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_DB_PORT: ${MONGO_DB_PORT}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_DB_TABLE_COLLECTION: ${MONGO_DB_TABLE_COLLECTION}
      MONGO_DB_REPLAY_COLLECTION: ${MONGO_DB_REPLAY_COLLECTION}
      SESSION_MANAGEMENT: ${SESSION_MANAGEMENT}
      TABLE: ${TABLE}
      TABLE_TOKEN: ${TABLE_TOKEN}
      REPLAY: ${REPLAY}
      CHOKIDAR_USEPOLLING: true
      NODE_OPTIONS: --max_old_space_size=8192
    volumes:
      - "./:/app"
    hostname: playing_cards
    tty: true
    # command: npm run dev
    networks:
      shared_network:
        ipv4_address: 172.16.0.10

  playing_cards_consumer:
    image: playing_cards_consumer
    container_name: playing_cards_consumer
    build:
      context: "./queue"
      dockerfile: "Dockerfile"
    ports:
      - "4000:4000"
    environment:
      MONGO_DB_HOST: ${MONGO_DB_HOST}
      MONGO_DB_USER: ${MONGO_DB_USER}
      MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_DB_PORT: ${MONGO_DB_PORT}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_DB_REPLAY_COLLECTION: ${MONGO_DB_REPLAY_COLLECTION}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
    volumes:
      - "./queue:/app"
    hostname: playing_cards_consumer
    tty: true
    networks:
      shared_network:
        ipv4_address: 172.16.0.7

networks:
  shared_network:
    external: true